{{- $configChecksum := include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Release.Name .Values.nameOverride }}
spec:
  selector:
    matchLabels:
      app: {{ default .Release.Name .Values.nameOverride }}
      release: {{ default .Release.Name .Values.nameOverride }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  template:
    metadata:
      annotations:
        configChecksum: {{ $configChecksum }}
      labels:
        app: {{ default .Release.Name .Values.nameOverride }}
        release: {{ default .Release.Name .Values.nameOverride }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ default .Release.Name .Values.nameOverride }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: https
              containerPort: 443
            - name: management
              containerPort: 3000
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: {{ $.Release.Name }}-config
              mountPath: /etc/kasmvnc
      volumes:
        - name: {{ $.Release.Name }}-cert
          secret:
            secretName: {{.Values.ingressRoute.certificate.name}}