{{- range $serviceName,$serviceValues := .Values.services }}
{{- if $serviceValues.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ default $serviceName $serviceValues.nameOverride }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ default $serviceName $serviceValues.nameOverride }}
  minReplicas: {{ $serviceValues.autoscaling.minReplicas }}
  maxReplicas: {{ $serviceValues.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $serviceValues.autoscaling.targetCPUUtilizationPercentage }}
---
{{- end }}
{{- end }}