{{ range $serviceName,$serviceValues := .Values.services }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{.Release.Name}}
spec:
  entryPoints:
    - {{$serviceValues.ingressRoute.entryPointName}}
  routes:
    - kind: Rule
      match: Host(`{{$serviceValues.ingressRoute.domain}}`)
      services:
        - kind: Service
          name: {{ .Release.Name }}
          namespace: {{ .Release.Namespace }}
          passHostHeader: true
          port: {{ $serviceValues.services.user1.service.port }}
{{- end }}