apiVersion: v1
kind: Service
metadata:
  name: {{ default .Release.Name .Values.nameOverride }}
spec:
  selector:
    app: {{ default .Release.Name .Values.nameOverride }}
    release: {{ default .Release.Name .Values.nameOverride }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: management