apiVersion: v2
name: kasm
description: Helm chart for Kasm
version: 1.0.0
dependencies:
  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 12.5.7
    repository: https://charts.bitnami.com/bitnami