services:
  peterfox:
    ingressRoute:
      domain: "peter-fox.edu.iits.tech"
      entryPointName: "websecure"
      certificate:
        name: peter-fox-cert
        clusterIssuer: letsencrypt
    nameOverride:
    image:
      repository: "kasmweb/ubuntu-focal-desktop"
      tag: "1.13.0"
      pullPolicy: "IfNotPresent"
    replicaCount: 1
    service:
      port: 6901
      externalPort: 80
    podSecurityContext:
      fsGroup: 2000
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 4096Mi
    livenessProbe:
      httpGet:
        path: "/"
        port: 6901
      initialDelaySeconds: 10
      periodSeconds: 60
    readinessProbe:
      httpGet:
        path: "/"
        port: 6901
      initialDelaySeconds: 10
      periodSeconds: 60
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    extraEnv:
      VNC_PW: "password"