config:
  network:
    protocol: http
    interface: 0.0.0.0
    websocket_port: auto
    use_ipv4: true
    use_ipv6: true
    ssl:
      pem_certificate: ${HOME}/.vnc/self.pem
      pem_key: ${HOME}/.vnc/self.pem
      require_ssl: false
    udp:
      public_ip: auto

services:
  peterfox:
    ingressRoute:
      domain: "peter-fox.edu.iits.tech"
      entryPointName: "websecure"
      certificate:
        name: peter-fox-cert
        clusterIssuer: letsencrypt
    nameOverride:
    image:
      repository: "kasmweb/ubuntu-focal-desktop"
      tag: "1.13.0"
      pullPolicy: "IfNotPresent"
    replicaCount: 1
    service:
      port: 6901
      externalPort: 6901
    podSecurityContext:
      fsGroup: 2000
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      requests:
        cpu: 2000m
        memory: 4096Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    extraEnv:
      VNC_PW: "password"