config:
  network:
    protocol: http
    interface: 0.0.0.0
    websocket_port: auto
    use_ipv4: true
    use_ipv6: true
    ssl:
      pem_certificate: ${HOME}/.vnc/self.pem
      pem_key: ${HOME}/.vnc/self.pem
      require_ssl: false
    udp:
      public_ip: auto

services:
  peterfox:
    ingressRoute:
      domain: "peter-fox.edu.iits.tech"
      entryPointName: "websecure"
      certificate:
        name: peter-fox-cert
        clusterIssuer: letsencrypt
    nameOverride:
    image:
      repository: "kasmweb/ubuntu-focal-desktop"
      tag: "1.13.0"
      pullPolicy: "IfNotPresent"
    replicaCount: 1
    service:
      port: 6901
      externalPort: 6901
    podSecurityContext:
      fsGroup: 2000
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      requests:
        cpu: 2000m
        memory: 4096Mi
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
    extraEnv:
      VNC_PW: "password"
      INST_SCRIPTS: "/ubuntu/install/tools/install_tools_deluxe.sh /ubuntu/install/misc/install_tools.sh /ubuntu/install/chrome/install_chrome.sh /ubuntu/install/chromium/install_chromium.sh /ubuntu/install/firefox/install_firefox.sh /ubuntu/install/sublime_text/install_sublime_text.sh /ubuntu/install/vs_code/install_vs_code.sh /ubuntu/install/nextcloud/install_nextcloud.sh /ubuntu/install/remmina/install_remmina.sh /ubuntu/install/only_office/install_only_office.sh /ubuntu/install/signal/install_signal.sh /ubuntu/install/gimp/install_gimp.sh /ubuntu/install/zoom/install_zoom.sh /ubuntu/install/obs/install_obs.sh /ubuntu/install/ansible/install_ansible.sh /ubuntu/install/terraform/install_terraform.sh /ubuntu/install/telegram/install_telegram.sh /ubuntu/install/thunderbird/install_thunderbird.sh  /ubuntu/install/cleanup/cleanup.sh"