ingressRoute:
  domain: "peter-fox.edu.iits.tech"
  entryPointName: "websecure"
  certificate:
    name: peter-fox-cert
    clusterIssuer: letsencrypt
nameOverride:
image:
  repository: "linuxserver/kasm"
  tag: "latest"
  pullPolicy: "IfNotPresent"
replicaCount: 1
securityContext:
  runAsNonRoot: false
resources:
  requests:
    cpu: 2000m
    memory: 4096Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
extraEnv:
  VNC_PW: "password"
  KASM_SVC_GAMEPAD: 0
  KASM_SVC_AUDIO_INPUT: 0
  KASM_SVC_UPLOADS: 0