wordpress:
  replicaCount: 2
  wordpressUsername: iits
  wordpressPassword: "zBMyVRE7tCWbItS83mu=9C3GyHyi@PGz"
  updateStrategy:
    type: Recreate
  mariadb:
    enabled: false
  externalDatabase:
    database: wordpress
    user: # set by argocd
    password: # set by argocd
  service:
    type: ClusterIP
  multisite:
    enable: true
    host: "wordpress.edu.iits.tech"
    networkType: subdomain
    enableNipIoRedirect: false
ingressRoute:
  domain: "wordpress.edu.iits.tech"
  entryPointName: "websecure"
  certificate:
    name: "wordpress-cert"
    clusterIssuer: letsencrypt