apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: {{ .Values.wordpress.externalDatabase.database }}
  POSTGRES_USER: {{ .Values.wordpress.externalDatabase.user }}
  POSTGRES_PASSWORD: {{ .Values.wordpress.externalDatabase.password }}