apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds
spec:
  selector:
    matchLabels:
      app: rds
  replicas: 1
  template:
    metadata:
      labels:
        app: rds
    spec:
      containers:
        - name: rds
          image: postgres
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              value: wordpress
            - name: POSTGRES_USER
              value: wordpress
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-data
          emptyDir: {}