{{ range $serviceName,$serviceValues := .Values.services }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  {{  $serviceValues.ingressRoute.certificate.name | default $serviceName }}
spec:
  secretName: {{ $serviceValues.ingressRoute.certificate.name}}
  issuerRef:
    name: {{ $serviceValues.ingressRoute.certificate.clusterIssuer}}
    kind: ClusterIssuer
  commonName: {{ $serviceValues.ingressRoute.domain}}
  privateKey:
    algorithm: "RSA"
    size: 4096
  dnsNames:
    - {{ $serviceValues.ingressRoute.domain}}
{{- end }}