{{ range $serviceName,$serviceValues := .Values.services }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{$serviceName}}
spec:
  entryPoints:
    - {{$serviceValues.ingressRoute.entryPointName}}
  routes:
    - match: Host(`{{$serviceValues.ingressRoute.domain}}`)
      services:
        - name: {{ $serviceName}}
          namespace: {{ $.Release.Namespace }}
          port: {{ $serviceValues.service.externalPort }}
  tls:
    secretName: {{$serviceValues.ingressRoute.certificate.name}}
    domains:
      - main: {{ $serviceValues.ingressRoute.domain}}

{{- end }}