apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-default-route-http
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`{host:.+}`)
      middlewares:
        - name: https-redirect
          namespace: {{.Release.Namespace}}
      services:
        - name: {{.Release.Name}}
          kind: Service
          namespace: {{ .Release.Namespace }}
          port: 443